#!/bin/bash

set -e
set -x

VERSION='1.5.2'
WGET_ARGS=""
WGET_ARGS="--limit-rate=1024k"
ARCH="amd64"

mkdir -p packages

wget https://github.com/kubernetes/kubernetes/releases/download/v${VERSION}/kubernetes.tar.gz -O /tmp/kubernetes.tar.gz --continue ${WGET_ARGS}

mkdir -p tmp
if [ ! -f tmp/kubernetes/cluster/centos ]; then
	( cd tmp; tar xfvz /tmp/kubernetes.tar.gz kubernetes/cluster/centos --strip=2 )
fi
. tmp/centos/config-build.sh

wget ${K8S_SERVER_DOWNLOAD_URL} -O /tmp/k8s-server.tar.gz --continue ${WGET_ARGS}

if [ ! -f tmp/hyperkube ]; then
	( cd tmp; tar xfvz /tmp/k8s-server.tar.gz '*/hyperkube' --strip=3 )
fi

( cd tmp; mkdir -p sbin/hyperkube ; cd sbin/hyperkube ;
	for i in kubectl apiserver scheduler proxy kubelet controller-manager kube-dns; do
		ln -svf /sbin/hyperkube $i;
        done
)
fpm -s dir -t rpm -a $ARCH -n k8s-hyperkube -v $VERSION --force \
		tmp/hyperkube=/sbin/hyperkube \
                tmp/sbin/hyperkube=/usr/lib \ 
