#!/bin/bash

set -e
set -x
VERSION='1.5.2'
PACKAGE_ITERATION=3
IMAGE_NAME='centos-fpm'
DOWNLOAD_CACHE='/tmp/k8s-rpm-download'
WORK_CACHE='/tmp/k8s-rpm-work'
DIST_URL="https://storage.googleapis.com/kubernetes-release/release/v${VERSION}/kubernetes-server-linux-amd64.tar.gz"

mkdir -p ${DOWNLOAD_CACHE} ${WORK_CACHE}

# Prepare fpm image
docker build -t $IMAGE_NAME -f Dockerfile-fpm.centos7 .

# Run packaging script in the container
docker run -it --rm  \
	-e TARGET_DIR=/packages \
	-e DOWNLOAD_CACHE=${DOWNLOAD_CACHE} \
	-e WORK_CACHE=${WORK_CACHE} \
	-e DIST_URL=${DIST_URL} \
	-e PACKAGE_ITERATION=${PACKAGE_ITERATION} \
	-v ${DOWNLOAD_CACHE}:${DOWNLOAD_CACHE} \
	-v ${WORK_CACHE}:${WORK_CACHE} \
	-v $(pwd)/packages:/packages \
	-v $(pwd)/do-packaging:/tmp/do-packaging \
	--entrypoint /bin/bash \
	${IMAGE_NAME} '/tmp/do-packaging'
